### ISSUE TITLE
Improve documentation/seeding

### ISSUE THREAD

**Issue by vaishnavmhetre** [mycarrysun/laravel-bands-vue-material#1]
1. Add instruction to run `npm install` with `composer install` to install node dependencies in README.md of repo
2. **240** save-many entries in seeds are not necessary. Find a more optimal count. Its just a dumb data for testing.

**Comment by mycarrysun** [comment]
Thanks for the feedback @vaishnavmhetre ! 
Seeding was required by the project but yes not necessary. Will reduce to 15.
